### ISSUE TITLE
[ERROR] Error 1146: Table 'wakapi.users' doesn't exist

### ISSUE THREAD

**Issue by Skillkiller** [muety/wakapi#171]
Hello,
I want to create a new Wakapi instance using Docker. As database I use mysql. I have passed the corresponding data as ENV. The connection also works so far and a table is created. But after that the ``20210213-add_has_data_field`` migration failed. It says the table does not exist, that is also so far correct but the DB is also new, should not the program create the table then accordingly itself?

Log:
```
wakapi_1     | Waiting for database to come up
wakapi_1     | wait-for-it.sh: waiting 60 seconds for mysql:3306
wakapi_1     | wait-for-it.sh: mysql:3306 is available after 0 seconds
wakapi_1     | 2021-04-13T19:10:31.314387103Z [INFO ] potentially running migration '20201103-rename_language_mappings_table'
wakapi_1     | 2021-04-13T19:10:31.317002455Z [INFO ] potentially running migration '20201106-migration_cascade_constraints'
wakapi_1     | 2021-04-13T19:10:31.320212581Z [INFO ] no need to migrate '20201106-migration_cascade_constraints'
wakapi_1     | 2021-04-13T19:10:31.320232685Z [INFO ] potentially running migration '20210202-fix_cascade_for_alias_user_constraint'
wakapi_1     | 2021-04-13T19:10:31.322522238Z [INFO ] no need to migrate '20210202-fix_cascade_for_alias_user_constraint'
wakapi_1     | 2021-04-13T19:10:31.337817102Z [INFO ] potentially running migration '20210206_drop_badges_column_add_sharing_flags'
wakapi_1     | 2021-04-13T19:10:31.338613648Z [INFO ] potentially running migration '20210213-add_has_data_field'
wakapi_1     | 2021-04-13T19:10:31.339162936Z [ERROR] migration '20210213-add_has_data_field' failed – Error 1146: Table 'wakapi.users' doesn't exist
wakapi_1     | panic: migration '20210213-add_has_data_field' failed – Error 1146: Table 'wakapi.users' doesn't exist
wakapi_1     | 
wakapi_1     | goroutine 1 [running]:
wakapi_1     | github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc0001a40a8, 0xcad32c, 0x1c, 0xc000403c00, 0x2, 0x2)
wakapi_1     | 	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:59 +0x8e
wakapi_1     | github.com/emvi/logbuch.(*Logger).Fatal(0xc0001f2000, 0xcad32c, 0x1c, 0xc000403c00, 0x2, 0x2)
wakapi_1     | 	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
wakapi_1     | github.com/emvi/logbuch.Fatal(...)
wakapi_1     | 	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
wakapi_1     | github.com/muety/wakapi/migrations.RunPostMigrations(0xc0002e7b90, 0xc0001c7680)
wakapi_1     | 	/src/migrations/migrations.go:60 +0x24a
wakapi_1     | github.com/muety/wakapi/migrations.Run(0xc0002e7b90, 0xc0001c7680)
wakapi_1     | 	/src/migrations/migrations.go:34 +0x65
wakapi_1     | main.main()
wakapi_1     | 	/src/main.go:130 +0x389
```

Docker-Compose cutted:
```
    wakapi:
        image: "n1try/wakapi"
        restart: "no"
        environment:
            - "WAKAPI_PASSWORD_SALT=REPLACED"
            - "ENVIRONMENT=production"
            - "WAKAPI_LISTEN_IPV4=0.0.0.0"
            - "WAKAPI_DB_HOST=mysql"
            - "WAKAPI_DB_PORT=3306"
            - "WAKAPI_DB_USER=wakapi"
            - "WAKAPI_DB_PASSWORD=REPLACED"
            - "WAKAPI_DB_NAME=wakapi"
            - "WAKAPI_DB_TYPE=mysql"
            - "WAKAPI_DB_MAX_CONNECTIONS=3"
            - "WAKAPI_MAIL_ENABLED=false"
            - "WAKAPI_ALLOW_SIGNUP=true"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.wakapi.loadbalancer.server.port=3000"
        networks:
            - proxy
            - mysql
```
