### ISSUE TITLE
`Unexpected end of JSON input` error when running in Docker with `dev` environment

### ISSUE THREAD

**Issue by jsbrain** [muety/wakapi#470]
**Describe the bug**

I'm experience weird while trying to deploy wakapi via Docker.

I tried the last 5 versions or so, only happens with the postgres adapter.

Tried running this example config on various hosts, local, server, doesn't matter:

```yml
version: "3.8"

services:
  wakapi:
    image: n1try/wakapi:2.6.1
    ports:
      - 3000:3000
    restart: always
    environment:
      # See README.md and config.default.yml for all config options
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD: "choose-a-password"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      ENVIRONMENT: "dev"

  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: "choose-a-password"
      POSTGRES_DB: "wakapi"
    volumes:
      - wakapi-db-data:/var/lib/postgresql/data

volumes:
  wakapi-db-data: {}

```

For me this results in:

```
wakapi-wakapi-1  | wait-for-it.sh: 192.168.178.43:38482 is available after 0 seconds
wakapi-wakapi-1  | 2023-02-28T13:38:05.862473541Z [INFO ] creating job queue 'wakapi.default' (1 workers)
wakapi-wakapi-1  | 2023-02-28T13:38:05.862527122Z [INFO ] creating job queue 'wakapi.processing' (5 workers)
wakapi-wakapi-1  | 2023-02-28T13:38:05.862545381Z [INFO ] creating job queue 'wakapi.reports' (1 workers)
wakapi-wakapi-1  | 2023-02-28T13:38:05.86257734Z [INFO ] creating job queue 'wakapi.imports' (1 workers)
wakapi-wakapi-1  | 2023-02-28T13:38:05.862615222Z [INFO ] creating job queue 'wakapi.housekeeping' (5 workers)
wakapi-wakapi-1  | 2023-02-28T13:38:05.866743522Z [ERROR] unexpected end of JSON input
wakapi-wakapi-1  | panic: unexpected end of JSON input
wakapi-wakapi-1  | 
wakapi-wakapi-1  | goroutine 1 [running]:
wakapi-wakapi-1  | github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00018b000?, {0xf1c822?, 0xf1c822?}, {0x0?, 0x0?, 0x0?})
wakapi-wakapi-1  | 	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
wakapi-wakapi-1  | github.com/emvi/logbuch.(*Logger).Fatal(0xc00018b000, {0xf1c822, 0x1c}, {0x0, 0x0, 0x0})
wakapi-wakapi-1  | 	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
wakapi-wakapi-1  | github.com/emvi/logbuch.Fatal(...)
wakapi-wakapi-1  | 	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
wakapi-wakapi-1  | github.com/muety/wakapi/config.readColors()
wakapi-wakapi-1  | 	/src/config/config.go:373 +0x145
wakapi-wakapi-1  | github.com/muety/wakapi/config.Load({0xefdf5a, 0x6})
wakapi-wakapi-1  | 	/src/config/config.go:425 +0x2fb
wakapi-wakapi-1  | main.main()
wakapi-wakapi-1  | 	/src/main.go:110 +0x53
```

Can anyone reproduce this?

**System information**
Please provide information on:
* Wakapi version: any?
* Operating system
    * If Linux: Ubuntu, Debian, MacOs
    * If Docker: any?
* Database (Postgres)
