### ISSUE TITLE
[ERROR] attempt to write a readonly database on startup

### ISSUE THREAD

**Issue by jostyee** [muety/wakapi#471]
**Describe the bug**
The latest docker image won't start:
```
...
wakapi    | 2023-03-04T11:57:38.451212786Z [INFO ] potentially running migration '20221028-fix_heartbeats_time_user_idx'
wakapi    | 2023-03-04T11:57:38.456457124Z [ERROR] attempt to write a readonly database (8)
wakapi    | panic: attempt to write a readonly database (8)
wakapi    |
wakapi    | goroutine 1 [running]:
wakapi    | github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00010ac80?, {0xc000cdcdb0?, 0xc000cdcdb0?}, {0x0?, 0x0?, 0x0?})
wakapi    | 	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
wakapi    | github.com/emvi/logbuch.(*Logger).Fatal(0xc00010ac80, {0xc000cdcdb0, 0x28}, {0x0, 0x0, 0x0})
wakapi    | 	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
wakapi    | github.com/emvi/logbuch.Fatal(...)
wakapi    | 	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
wakapi    | github.com/muety/wakapi/migrations.RunSchemaMigrations(0x0?, 0x0?)
wakapi    | 	/src/migrations/migrations.go:81 +0x65
wakapi    | github.com/muety/wakapi/migrations.Run(0xc000c920d0?, 0x1?)
wakapi    | 	/src/migrations/migrations.go:75 +0x34
wakapi    | main.main()
wakapi    | 	/src/main.go:154 +0x71d
```

my docker-compose.yml:
```yml
version: '3.3'

services:
  wakapi:
    image: 'ghcr.io/muety/wakapi:latest'
    container_name: wakapi
    restart: always
    ports:
      - '3000:3000'
    environment:
      - WAKAPI_PASSWORD_SALT=$SALT
    volumes:
      - './data:/data'
```

revert to 2.6.1 works.

**System information**
Please provide information on:
* Wakapi version
  2.6.2
* Operating system
    * Docker: latest
* Database
  SQLite
