### ISSUE TITLE
Unraid: unable to open database file: out of memory (14)

### ISSUE THREAD

**Issue by manuel-rw** [muety/wakapi#526]
**Describe the bug**

When trying to run Wakapi on Unraid, the container will stop immideatly with the following log:

``` 
2023-09-22T22:23:31.244632728+02:00 [ERROR] unable to open database file: out of memory (14)
2023-09-22T22:23:31.244641106+02:00 [ERROR] could not open database
panic: could not open database

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc0000e0000?, {0x116b2c5?, 0x116b2c5?}, {0x0?, 0x0?, 0x0?})
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:57 +0x3f
github.com/emvi/logbuch.(*Logger).Fatal(0xc0000e0000, {0x116b2c5, 0x17}, {0x0, 0x0, 0x0})
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x77
github.com/emvi/logbuch.Fatal(...)
        /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
main.main()
        /src/main.go:145 +0x6d8
2023-09-22T22:23:19.296427774+02:00 [INFO ] disabling data retention policy, keeping data forever
2023-09-22T22:23:19.296436598+02:00 [WARN ] with sqlite, only a single connection is supported
2023-09-22T22:23:19.296448106+02:00 [INFO ] Wakapi 2.8.2
2023-09-22T22:23:19.296450505+02:00 [INFO ] starting with sqlite3 database
```

The generated docker command by dynamix is:
```bash
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='wakapi' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="wakapi" -e 'WAKAPI_PASSWORD_SALT'='XXXXXXXXXXX' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:5000]/' -l net.unraid.docker.icon='https://github.com/muety/wakapi/raw/master/static/assets/images/logo-gh.svg' -p '5000:3000/tcp' -v '/mnt/user/appdata/wakapi/data':'/data':'rw' 'ghcr.io/muety/wakapi:latest' 
```

I replaced the ``/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker`` on my Windows system with ``docker`` and replaced all invalid values for the Windows CMD (eg. ``-v 'Key':'Value' by ``-v "Key: Value") as Windows doesn't seem to be able to cope with them:

```
docker create --name='wakapi' --net='bridge' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Tower" -e HOST_CONTAINERNAME="wakapi" -e "WAKAPI_PASSWORD_SALT=XXXXXXX" -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:5000]/' -l net.unraid.docker.icon='https://github.com/muety/wakapi/raw/master/static/assets/images/logo-gh.svg' -p '5000:3000/tcp' -v "XXXXXX:rw" ghcr.io/muety/wakapi:latest
```

Using that, it seems to work fine on Windows but not on my Unraid machine.

My system has enough memory and CPU is not busy.
![image](https://github.com/muety/wakapi/assets/30572287/0a1dbd0d-ab12-4227-9a30-31e249039656)

**System information**
* Wakapi version ``ghcr.io/muety/wakapi, latest, 351c60c5154d, 2 weeks ago, 43.8MB``
* Operating system
    * If Linux: ``Linux Tower 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz GenuineIntel GNU/Linux``
    * If Docker: ``Docker version 20.10.18, build b40c2f6``
* Database ``Sqlite``

**Comment by muety** [comment]
I'm unfamiliar with Unraid specifically and I haven't heard of dynamix (whats is it?), so I probably can't give very targeted support here. I'd assume it's a permission issue, though. Please make sure that the directory you're trying to mount into the container (`/mnt/user/appdata/wakapi/data`) (a) exists and (b) is writable by user id 1000.

**Comment by manuel-rw** [comment]
Hi, thanks for the reply.
Dynamix is the modular plugin and feature management for Unraid. Although the Docker command is available as usual in the shell, Unraid seems to execute some alias.
Unraid itself is a NAS management system, but that shouldn't be the cause here.

I did check for the directory - it exists. The db file was never created though. I did ensure that the docker user has permission to write and read - but Unraid's default user sometimes conflicts with the user IDs.
I'll check tomorrow if I really use 1000 or not and report it back here.

**Comment by muety** [comment]
You could also try to make the directory world-writable, at least for debugging.

**Comment by manuel-rw** [comment]
After running ``chmod 777 data/ -R`` on the mounted directory, I can confirm that it is a permission issue (**DO NOT DO THIS IN PRODUCTION**).
I can read out the UID & GID using the following commands:

```sh
root@Tower:/mnt/user/appdata/wakapi# docker exec -u nobody -it wakapi whoami
nobody
root@Tower:/mnt/user/appdata/wakapi# id nobody
uid=99(nobody) gid=100(users) groups=100(users),98(nobody)
```

Adding the parameter ``--user 99:100`` to the "Extra parameters" resolved it.
I will publish a template, so other users won't have to figure this out themselves.

**Comment by Reed-yang** [comment]
same issue `unable to open database file: out of memory (14)` for hosting on Azure Kubernetes Service, Already made PVC permission read and write, everything seems fine, but fails.
What can I do?
New to AKS, need your support pls (:

**Comment by anisjonischkeit** [comment]
If anyone else has this issue with sqlite in docker, here's my working compose file 

https://github.com/muety/wakapi/pull/649#issuecomment-2133332890

**Comment by wayanjimmy** [comment]
I encountered the same error deploying to Kubernetes with Litestream. Here is my StatefulSet YAML configuration that worked.

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wakaapi-1
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: wakaapi
  template:
    metadata:
      labels:
        app: wakaapi
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
        - name: init-litestream
          image: litestream/litestream:0.3.9
          args:
            [
              "restore",
              "-if-db-not-exists",
              "-if-replica-exists",
              "-v",
              "/data/wakapi.db",
            ]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: configmap
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          env:
            - name: LITESTREAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: wakaapi
                  key: LITESTREAM_ACCESS_KEY_ID
            - name: LITESTREAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: wakaapi
                  key: LITESTREAM_SECRET_ACCESS_KEY
      containers:
        - name: wakaapi
          image: ghcr.io/muety/wakapi:2.11.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /data
          env:
            - name: WAKAPI_EXPOSE_METRICS
              value: "true"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        - name: litestream
          image: litestream/litestream:0.3.9
          args: ["replicate"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: configmap
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          env:
            - name: LITESTREAM_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: wakaapi
                  key: LITESTREAM_ACCESS_KEY_ID
            - name: LITESTREAM_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: wakaapi
                  key: LITESTREAM_SECRET_ACCESS_KEY
          ports:
            - name: metrics
              containerPort: 9090
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: wakaapi-pvc
        - name: configmap
          configMap:
            name: wakaapi
```
