### ISSUE TITLE
Self Hosted SMTP returns i/o error

### ISSUE THREAD

**Issue by KOT4N** [muety/wakapi#536]
**Describe the bug**
I wanna use self-hosted smtp for wakapi but got i/o error. In smtp logs I got NOTHING about it. Not password error, not invalid username. Absolutely nothing.

```
smtp:
    host: smtp.domain
    port: 465
    username: waka@domain
    password: 1111111
    tls: true
```

**System information**
* Wakapi version 2.9.1
* Operating system Ubuntu 22.04
* Database (SQLite, MySQL, ... ?) PSQL and SQLite
