### ISSUE TITLE
Error connecting to mysql database

### ISSUE THREAD

**Issue by jared-a-lloyd** [muety/wakapi#549]
Wakapi Version: 2.9.3
DB: MySQL 8 (docker image)

I am running wakapi (ghcr.io/muety/wakapi:latest) on my ubuntu22.04 homelab in a docker container, with a separate container for my mysql database. Both containers share the "backend" network.

My wakapi docker compose environment declaration includes this for the db:
      - WAKAPI_DB_HOST=home-sql-server.backend
      - WAKAPI_DB_PORT=3306
      - WAKAPI_DB_USER=wakapi_user
      - WAKAPI_DB_TYPE=mysql
      - WAKAPI_DB_TYPE=utf8mb4
      - WAKAPI_DB_NAME=wakapi
      - WAKAPI_DB_MAX_CONNECTIONS=1
WAKAPI_DB_PASSWORD is defined in a .env file

If the above are commented out the setup works fine (i.e. with sqlite).
I don't believe that I have a reverse proxy set up, but when starting the wakapi container with this configuration I get these logs:

```
wakapi  | Waiting for database to come up
wakapi  | wait-for-it.sh: waiting 60 seconds for home-sql-server.backend:3306
wakapi  | wait-for-it.sh: home-sql-server.backend:3306 is available after 0 seconds
wakapi  | 2023-11-15T16:36:38.069917605Z [WARN ] failed to parse reverse proxy ip
wakapi  | 2023-11-15T16:36:38.069934786Z [INFO ] disabling data retention policy, keeping data forever
wakapi  | 2023-11-15T16:36:38.06995099Z [INFO ] Wakapi 2.9.3
wakapi  | 2023-11-15T16:36:38.06995539Z [INFO ] starting with utf8mb4 database
wakapi  | panic: runtime error: invalid memory address or nil pointer dereference
wakapi  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e9582]
wakapi  | 
wakapi  | goroutine 1 [running]:
wakapi  | database/sql.(*DB).SetMaxIdleConns(0x0?, 0x0?)
wakapi  |       /usr/local/go/src/database/sql/sql.go:959 +0x22
wakapi  | main.main()
wakapi  |       /src/main.go:155 +0x78c
wakapi  | Waiting for database to come up
wakapi exited with code 0
wakapi  | wait-for-it.sh: waiting 60 seconds for home-sql-server.backend:3306
wakapi  | wait-for-it.sh: home-sql-server.backend:3306 is available after 0 seconds
wakapi  | 2023-11-15T16:36:38.977677287Z [WARN ] failed to parse reverse proxy ip
wakapi  | 2023-11-15T16:36:38.977690278Z [INFO ] disabling data retention policy, keeping data forever
wakapi  | 2023-11-15T16:36:38.977704945Z [INFO ] Wakapi 2.9.3
wakapi  | 2023-11-15T16:36:38.977708786Z [INFO ] starting with utf8mb4 database
wakapi  | panic: runtime error: invalid memory address or nil pointer dereference
wakapi  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e9582]
wakapi  | 
wakapi  | goroutine 1 [running]:
wakapi  | database/sql.(*DB).SetMaxIdleConns(0x0?, 0x0?)
wakapi  |       /usr/local/go/src/database/sql/sql.go:959 +0x22
wakapi  | main.main()
wakapi  |       /src/main.go:155 +0x78c
```

**Comment by muety** [comment]
Hi @jared-a-lloyd, can you please share your Docker Compose file (with all sensitive data redacted), please?

**Comment by jared-a-lloyd** [comment]
Hi @muety, thanks for the quick reply. 
Here is my docker compose:

```
version: "3"

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    volumes:
      - ./db:/data
    container_name: wakapi
    env_file:
      - .env
    environment:
      - WAKAPI_PASSWORD_SALT=<redacted>
      - ENVIRONMENT=production
      - WAKAPI_PUBLIC_URL=<redacted>
      - WAKAPI_DISABLE_FRONTPAGE=true
      - WAKAPI_EXPOSE_METRICS=true
      - WAKAPI_PORT=<redacted>
      - WAKAPI_INSECURE_COOKIES=true
      - WAKAPI_LISTEN_IPV4=0.0.0.0
      - WAKAPI_HEARTBEAT_MAX_AGE=20000h
      - WAKAPI_DB_HOST=home-sql-server.backend
      - WAKAPI_DB_PORT=3306
      - WAKAPI_DB_USER=wakapi_user
      - WAKAPI_DB_TYPE=mysql
      - WAKAPI_DB_TYPE=utf8mb4
      - WAKAPI_DB_NAME=wakapi
      - WAKAPI_DB_MAX_CONNECTIONS=1
    restart: unless-stopped
    ports:
      - <redacted>
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
```
In the .env I have:
```
WAKAPI_DB_PASSWORD=<redacted>
```
