### ISSUE TITLE
Wakapi instance cannot start

### ISSUE THREAD

**Issue by cfouche3005** [muety/wakapi#573]
**Describe the bug**
Wakapi doesn't start after update to 2.10.0

logs: 
```
Waiting for database to come up
wait-for-it.sh: waiting 60 seconds for localhost:5432
wait-for-it.sh: localhost:5432 is available after 0 seconds
2023-12-02T18:11:28.092520755Z [ERROR] failed to read config: yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `7_days` into bool
panic: failed to read config: yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `7_days` into bool
goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x2347fa0?, {0x111beaf?, 0x111beaf?}, {0xc000339860?, 0xc000339860?, 0x1?})
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:59 +0x5f
github.com/emvi/logbuch.(*Logger).Fatal(0x2347fa0, {0x111beaf, 0x19}, {0xc000339860, 0x1, 0x1})
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x72
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
github.com/muety/wakapi/config.Load({0x110c765, 0xa}, {0x1108b1b, 0x7})
	/src/config/config.go:412 +0x15e
main.main()
	/src/main.go:120 +0x138
```

Env var :
WAKAPI_LEADERBOARD_SCOPE=all_time

**System information**
Please provide information on:
* Wakapi version : 2.10.0
* Operating system
    * Docker: 	ghcr.io/muety/wakapi:latest (2.10.0)
* Database (SQLite, MySQL, ... ?) : PostegreSQL

**Comment by muety** [comment]
Seems like I made a copy & paste mistake in `config.default.yml`. Will push a fix in a sec! In the meanwhile, seting `WAKAPI_LEADERBOARD_ENABLED=true` shoud do as a workaround.

**Comment by cfouche3005** [comment]
thank for your response, I have tested the workaround and it doesn't seem to works

**Comment by muety** [comment]
Please try to re-pull the image and start again.

**Comment by cfouche3005** [comment]
Done and it works, thanks for your reactivity.
![image](https://github.com/muety/wakapi/assets/51720655/fba6943b-85bc-46ca-abf0-30e85d7767d0)

**Comment by cfouche3005** [comment]
I can also confirm that `WAKAPI_IMPORT_BATCH_SIZE=0` work :
![image](https://github.com/muety/wakapi/assets/51720655/c3fb8f70-63e6-4c34-bc22-617d90a631ac)

**Comment by MSWS** [comment]
Can confirm this does not appear to be working for me still with the latest version.

```yml
version: '3.8'

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    restart: always
    ports:
      - "3002:3002"
    environment:
      [...]
      WAKAPI_DB_TYPE: "mysql"
      WAKAPI_ALLOW_SIGNUP: "false"
      WAKAPI_DISABLE_FRONTPAGE: "true"
      WAKAPI_EXPOSE_METRICS: "true"
      WAKAPI_LEADERBOARD_ENABLED: "true"
      WAKAPI_LEADERBOARD_SCOPE: "month"
```

```
2023-12-03T08:34:15.888275565Z [ERROR] failed to read config: yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `7_days` into bool
panic: failed to read config: yaml: unmarshal errors:
  line 19: cannot unmarshal !!str `7_days` into bool
```
