### ISSUE TITLE
Doesn't start after update to 2.10.0

### ISSUE THREAD

**Issue by mawoka-myblock** [muety/wakapi#575]
**Describe the bug**
```
wakapi-wakapi-1  | goroutine 1 [running]:
wakapi-wakapi-1  | github.com/emvi/logbuch.(*StandardFormatter).Pnc(0x2347fa0?, {0x111beaf?, 0x111beaf?}, {0xc000035810?, 0xc000035810?, 0x1?})
wakapi-wakapi-1  |      /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/standard_formatter.go:59 +0x5f
wakapi-wakapi-1  | github.com/emvi/logbuch.(*Logger).Fatal(0x2347fa0, {0x111beaf, 0x19}, {0xc000035810, 0x1, 0x1})
wakapi-wakapi-1  |      /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/logger.go:132 +0x72
wakapi-wakapi-1  | github.com/emvi/logbuch.Fatal(...)
wakapi-wakapi-1  |      /go/pkg/mod/github.com/emvi/logbuch@v1.2.0/funcs.go:55
wakapi-wakapi-1  | github.com/muety/wakapi/config.Load({0x110c765, 0xa}, {0x1108b1b, 0x7})
wakapi-wakapi-1  |      /src/config/config.go:412 +0x15e
wakapi-wakapi-1  | main.main()
wakapi-wakapi-1  |      /src/main.go:120 +0x138
wakapi-wakapi-1  | 2023-12-04T12:03:58.966768306Z [ERROR] failed to read config: yaml: unmarshal errors:
wakapi-wakapi-1  |   line 19: cannot unmarshal !!str `7_days` into bool
wakapi-wakapi-1  | panic: failed to read config: yaml: unmarshal errors:
wakapi-wakapi-1  |   line 19: cannot unmarshal !!str `7_days` into bool
wakapi-wakapi-1  | 
```

**System information**
Please provide information on:
* Wakapi version: 2.10.0
* Operating system: Linux
    * If Docker: which image and tag?: latest
* Database (SQLite, MySQL, ... ?): sqlite

### Docker-Compose.yml
```yaml
version: "3"
services:
  wakapi:
    restart: unless-stopped
    image: ghcr.io/muety/wakapi:latest
    user: root
    environment:
      WAKAPI_PASSWORD_SALT: PEPPER
    volumes:
      - ./data:/data
    ports:
      - 8079:3000
```
