### ISSUE TITLE
Error after updating to `2.10.1`

### ISSUE THREAD

**Issue by DenuxPlays** [muety/wakapi#584]
**Describe the bug**
Updated from 2.10.0 to 2.10.1 and got the following error:

![image](https://github.com/muety/wakapi/assets/83671398/128f0545-2f05-43cf-89d8-04b1d1ddd2e2)

Everything worked fine before.<br>
The thing I did was:
```sh
docker compose down -v
docker compose pull
docker compose up -d
```

Used docker compose with the following file:
```yml
version: "3.8"
services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    restart: unless-stopped
    container_name: wakapi
    ports:
      - "127.0.0.1:7523:3000"
    volumes:
      - ./data:/data
    environment:
      WAKAPI_PASSWORD_SALT: ${WAKAPI_PASSWORD_SALT}
      WAKAPI_PUBLIC_URL: ${WAKAPI_PUBLIC_URL}
      WAKAPI_DB_HOST: db
      WAKAPI_DB_PORT: 3306
      WAKAPI_DB_USER: ${DATABASE_USERNAME}
      WAKAPI_DB_PASSWORD: ${DATABASE_PASSWORD}
      WAKAPI_DB_NAME: ${DATABASE_NAME}
      WAKAPI_DB_TYPE: mysql
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: ${TZ}
    healthcheck:
      test: [ 'CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized' ]
      timeout: 5s
      interval: 5s
      retries: 5
```
