### ISSUE TITLE
Too many requests on signup page

### ISSUE THREAD

**Issue by kcoderhtml** [muety/wakapi#674]
Hi! I just found this project and love it so far! I keep having an issue with the signup page serving a "too many requests" error after 3-4 page loads after startup; simply restarting the container fixes the issue, but then after 3-4 more page loads it happens again.

**System information**
* Instance: https://w.dunkirk.sh/signup
* Wakapi version: `2.11.2`
* Operating system: Docker with the latest tag from ghcr
* Database: Postgres hosted locally on the machine

Here's my docker compose; it's super simple and basically the same as the README sample minus the Postgres container.
```yaml
services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    ports:
      - 35555:3000
    restart: always
    environment:
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "usr_wakapi"
      WAKAPI_DB_USER: "usrname"
      WAKAPI_DB_PASSWORD: "xxxx"
      WAKAPI_DB_HOST: "hackclub.app"
      WAKAPI_DB_PORT: "5432"
      ENVIRONMENT: "prod"
```

Docker container logs:

```dockerlogs
wakapi-1  | 2024-09-08T18:03:46.329908551Z [INFO ] [request] status=429, method=GET, uri=/signup, duration=47.026µs, bytes=18, addr=172.18.0.1:41306, user=-
```
