### ISSUE TITLE
Fail to start docker container after update to version 2.12.0 with error migration failed

### ISSUE THREAD

**Issue by zoonderkins** [muety/wakapi#684]
**Describe the bug**

I got this error message 

```
wakapi  | {"time":"2024-10-05T08:56:15.96090864Z","level":"WARN","msg":"failed to parse reverse proxy ip ranges"}
wakapi  | {"time":"2024-10-05T08:56:15.961549236Z","level":"INFO","msg":"disabling data retention policy, keeping data forever"}
wakapi  | {"time":"2024-10-05T08:56:15.961681413Z","level":"WARN","msg":"with sqlite, only a single connection is supported"}
wakapi  | {"time":"2024-10-05T08:56:15.961882919Z","level":"INFO","msg":"Wakapi","version":"2.12.0\n"}
wakapi  | {"time":"2024-10-05T08:56:15.961992182Z","level":"INFO","msg":"starting with database","dialect":"sqlite3"}
wakapi  | {"time":"2024-10-05T08:56:15.965162398Z","level":"INFO","msg":"potentially running migration","name":"20201103-rename_language_mappings_table"}
wakapi  | {"time":"2024-10-05T08:56:15.967797735Z","level":"INFO","msg":"potentially running migration","name":"20201106-migration_cascade_constraints"}
wakapi  | {"time":"2024-10-05T08:56:15.968027674Z","level":"INFO","msg":"not attempting to drop and regenerate constraints on sqlite"}
wakapi  | {"time":"2024-10-05T08:56:15.968103586Z","level":"INFO","msg":"potentially running migration","name":"20210202-fix_cascade_for_alias_user_constraint"}
wakapi  | {"time":"2024-10-05T08:56:15.968189686Z","level":"INFO","msg":"not attempting to drop and regenerate constraints on sqlite"}
wakapi  | {"time":"2024-10-05T08:56:15.968266109Z","level":"INFO","msg":"potentially running migration","name":"20220403-drop_user_project_idx"}
wakapi  | {"time":"2024-10-05T08:56:15.969374507Z","level":"INFO","msg":"no need to migrate","name":"20220403-drop_user_project_idx"}
wakapi  | {"time":"2024-10-05T08:56:15.96947794Z","level":"INFO","msg":"potentially running migration","name":"20220930-drop_heartbeats_entity_idx"}
wakapi  | {"time":"2024-10-05T08:56:15.970888462Z","level":"INFO","msg":"potentially running migration","name":"20221002-fix_summary_id_types"}
wakapi  | {"time":"2024-10-05T08:56:15.971040215Z","level":"INFO","msg":"potentially running migration","name":"20221028-fix_heartbeats_time_user_idx"}
wakapi  | {"time":"2024-10-05T08:56:15.973020971Z","level":"ERROR","msg":"migration failed","error":"attempt to write a readonly database (8)"}
```

**System information**
Please provide information on:
* Wakapi version: `2.12.0`
* Operating system
    * If Docker: `ghcr.io/muety/wakapi:latest`
* Database: SQLite

**Comment by zoonderkins** [comment]
I found the solution
 - run as root user

```
chmod -R 777 data/wakapi.db
UID=${UID} GID=${GID} docker compose up -d
```

**Comment by muety** [comment]
Can you please give instructions on how to reproduce this? Perhaps provide the exact `docker run` command you're using? When I simply run the official images, Wakapi boots up fine in the container.

**Comment by zoonderkins** [comment]
Here is my docker compose yaml on Debian 12 64bit
I'm running docker as root user 

```
cat docker-compose.yml
services:
    muety:
        ports:
            - '3000:3000'
        environment:
            - WAKAPI_PASSWORD_SALT='xxxxx'
            - WAKAPI_EXPOSE_METRICS=true
        volumes:
            - './data:/data:rw'
        container_name: wakapi
        image: 'ghcr.io/muety/wakapi:latest'
        restart: always
```
