### ISSUE TITLE
SMTP Connection Error: Unable to Connect to Sendinblue on TLS/SSL Ports (587/465) in Helm-deployed Wakapi

### ISSUE THREAD

**Issue by llulioscesar** [muety/wakapi#770]
**Describe the bug**
When deploying Wakapi via Helm in a Kubernetes environment using PostgreSQL, the SMTP configuration for Sendinblue fails to establish a secure connection. Emails are not sent because the connection either terminates with an "EOF" error or fails during the TLS/SSL handshake on both port 587 and port 465.

Steps to reproduce the bug:
Deploy Wakapi using Helm in a Kubernetes cluster.

Configure the SMTP settings with the following values:
```
mail:
    enabled: true
    provider: smtp
    sender: no-reply@xxxxx.xxx
    smtp:
      host: smtp-relay.sendinblue.com
      password: xxxxxxxxx
      port: 465
      tls: true
      username: xxxxxxx
      skip_verify: false
```
````
{"time":"2025-03-25T15:21:52.148237667Z","level":"INFO","msg":"[request]","status":302,"method":"POST","uri":"/reset-password","duration":2886448,"bytes":0,"addr":"181.236.161.222","user":"-"}
{"time":"2025-03-25T15:21:52.162297378Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/","duration":943874,"bytes":8855,"addr":"181.236.161.222","user":"-"}
{"time":"2025-03-25T15:22:43.265420312Z","level":"ERROR","msg":"failed to send password reset mail","userID":"juliocaicedo","error":"EOF"}
{"time":"2025-03-25T15:28:45.154980571Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/login","duration":1002166,"bytes":3976,"addr":"181.236.161.222","user":"-"}
````

```
mail:
    enabled: true
    provider: smtp
    sender: no-reply@xxxxx.xxx
    smtp:
      host: smtp-relay.sendinblue.com
      password: xxxxxxxxx
      port: 587
      tls: false
      username: xxxxxxx
      skip_verify: false
```
````
{"time":"2025-03-25T15:39:48.26831941Z","level":"INFO","msg":"[request]","status":302,"method":"POST","uri":"/reset-password","duration":3790606,"bytes":0,"addr":"181.236.161.222","user":"-"}
{"time":"2025-03-25T15:39:48.282313428Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/","duration":1689170,"bytes":8855,"addr":"181.236.161.222","user":"-"}
{"time":"2025-03-25T15:39:49.967723434Z","level":"ERROR","msg":"failed to send password reset mail","userID":"juliocaicedo","error":"smtp: server requires authentication, but no authentication is provided"}
````

Attempt to send a test email from Wakapi.

Observe that the connection fails with TLS/SSL errors (e.g., "EOF").

Expected behavior:
Wakapi should successfully connect to Sendinblue's SMTP server and send emails using the provided settings.

Actual behavior:
The connection fails with TLS/SSL errors on port 587 and port 465, preventing email delivery.

System information:

Wakapi version: ghcr.io/muety/wakapi:latest

Operating system: Kubernetes environment (Linux-based)

Database: PostgreSQL (installed via Helm)

**Comment by muety** [comment]
The error message you're seeing is only displayed if either username or password are an empty string, see here: https://github.com/muety/wakapi/blob/bc2096f4117275d110a84f5b367aa8fdb4bd87ba/services/mail/smtp.go#L71

Are you sure your config is being picked up properly? Potentially wrap username and password inside quotes. Also make sure that there are no (empty) environment variables that override your YAML config. Vice versa, you can also try to explicitly _do_ set the mail config via env. vars.

Also, can you confirm that outside of Kubernetes, your mail setup is working?

**Comment by llulioscesar** [comment]
> El mensaje de error que estás viendo solo se muestra si el nombre de usuario o la contraseña son una cadena vacía, consulta aquí:
> 
> [wakapi/servicios/mail/smtp.go](https://github.com/muety/wakapi/blob/bc2096f4117275d110a84f5b367aa8fdb4bd87ba/services/mail/smtp.go#L70-L72)
> 
> Líneas 70 a 72 en [bc2096f](/muety/wakapi/commit/bc2096f4117275d110a84f5b367aa8fdb4bd87ba)
> 
>  si  len ( s.config.nombredeusuario ) == 0 || len ( s.config.contraseña ) == 0 {​​​​​​​​    
>  	 Errores de retorno . Nuevo ( "smtp: el servidor requiere autenticación, pero no se proporciona" )
> }
> ¿Estás seguro de que tu configuración se está detectando correctamente? Puedes escribir el nombre de usuario y la contraseña entre comillas. También asegúrate de que no haya variables de entorno (vacías) que anulen tu configuración YAML. Por otro lado, también puedes intentar configurar explícitamente _la_ configuración de correo mediante variables de entorno.
> 
> Además, ¿puedes confirmar que, fuera de Kubernetes, tu configuración de correo funciona?

I'm sharing my configuration with you.

If I set port 587, I get an authentication error. If I set port 465, I get an EOF error.

As you can see in the initial logs I shared at the beginning of this thread,

```
  mail:
    enabled: true
    provider: null
    sender: no-reply@wakapi.dev
    smtp:
      host: smtp-relay.sendinblue.com
      password: "JKEHtMrSmCDs6cVT"
      port: 587
      tls: false
      username: "746346001@smtp-brevo.com"
```

```
{"time":"2025-03-26T00:58:03.52441009Z","level":"INFO","msg":"[request]","status":302,"method":"POST","uri":"/reset-password","duration":4946985,"bytes":0,"addr":"181.236.161.222","user":"-"}
{"time":"2025-03-26T00:58:03.538498009Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/","duration":1452278,"bytes":9425,"addr":"181.236.161.222","user":"-"}
{"time":"2025-03-26T00:58:05.208895879Z","level":"ERROR","msg":"failed to send password reset mail","userID":"juliocaicedo","error":"smtp: server requires authentication, but no authentication is provided"}
```

IF I enter the pod and run
```
echo $WAKAPI_MAIL_SMTP_PASSWORD
echo $WAKAPI_MAIL_SMTP_USERNAME
```
I can see the corresponding values

I installed it with the following chart
```
helm repo add wakapi https://ricristian.github.io/wakapi-helm-chart/
helm repo update
helm install -f own-values.yml wakapi-app wakapi/wakapi
```

```
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
exposeMetrics: false
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/muety/wakapi
  tag: ''
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
nameOverride: ''
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 2Gi
  storageClass: longhorn-simple
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: LoadBalancer
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
wakapi_config:
  app:
    aggregation_time: '02:15'
    custom_languages:
      jsx: JSX
      vue: Vue
    inactive_days: 7
  db:
    charset: null
    dialect: postgres
    host: xxxxxxxxxxxxxx
    max_conn: 2
    name: xxxxxxx
    password: xxxxxxxxxxxxxxxxx
    port: 5432
    ssl: false
    user: wakatime
  env: prod
  mail:
    enabled: true
    provider: null
    sender: no-reply@wakapi.dev
    smtp:
      host: smtp-relay.sendinblue.com
      password: "JKEHtMrSmCDs6cVT"
      port: 587
      tls: false
      username: "746346001@smtp-brevo.com"
  security:
    allow_signup: false
    cookie_max_age: 172800
    expose_metrics: false
    insecure_cookies: true
    password_salt: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  server:
    base_path: /
    listen_ipv4: 0.0.0.0
    listen_ipv6: null
    port: 3000
    tls_cert_path: null
    tls_key_path: null
    public_url: https://waka.xxxxxx.xxxx
  sentry: {}
```
