### ISSUE TITLE
Login doesn't work behind nginx reverse proxy

### ISSUE THREAD

**Issue by JPFrancoia** [muety/wakapi#790]
Hi,

I have wakapi deployed with the following Kubernetes manifest (I'm not fond of Helm, and wakapi is simple to deploy anyway):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wakapi
  labels:
    app: wakapi-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wakapi-api
  template:
    metadata:
      labels:
        app: wakapi-api
    spec:
      containers:
        - name: wakapi-api
          image: ghcr.io/muety/wakapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: WAKAPI_DB_TYPE
              value: "postgres"
            - name: WAKAPI_DB_NAME
              value: "wakapi"
            - name: WAKAPI_DB_USER
              value: "wakapi"
            - name: WAKAPI_DB_HOST
              value: "wakapi-db"
            - name: WAKAPI_DB_PORT
              value: "5432"
            - name: WAKAPI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wakapi
                  key: POSTGRES_PASSWORD
            - name: WAKAPI_ALLOW_SIGNUP
              value: "true"
            - name: WAKAPI_INVITE_CODES
              value: "false"
            - name: WAKAPI_DISABLE_FRONTPAGE
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: wakapi-api
spec:
  selector:
    app: wakapi-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wakapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
    - host: wakapi.fancydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wakapi-api
                port:
                  number: 3000
  tls:
    - hosts:
        - wakapi.fancydomain.com
      secretName: letsencrypt-cluster-issuer
```

I excluded the DB for brevity, it's not relevant here.

The deployment kind works, if I run `kubectl port-forward svc/wakapi-api 3000:3000`  I can then hit `localhost:3000` in my browser, I can create a user, see the summary page (empty for now), and all the other pages. Everything looks good up until now.

Problems arise with the ingress policy, nginx and the login page. The ingress policy above works, hitting `https://wakapi.fancydomain.com` does show the frontend normally. I can go to the login page. I can enter my user name and password, and click login. But then I'm immediately redirected to the home page, and if I try to visit `/summary`, I'm sent back to the login page.

It's as if the login isn't taken into account. The logs of the wakapi pod say:

```
{"time":"2025-05-19T16:20:12.144841364Z","level":"INFO","msg":"👉 Listening for HTTP... ✅","address":"0.0.0.0:3000"}
{"time":"2025-05-19T16:20:18.149967666Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/login","duration":7201446,"bytes":3986,"addr":"192.168.0.1","user":"-"}
{"time":"2025-05-19T16:20:50.372218698Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/login","duration":1280576,"bytes":3986,"addr":"192.168.0.1","user":"-"}
{"time":"2025-05-19T16:20:52.962210841Z","level":"INFO","msg":"[request]","status":302,"method":"POST","uri":"/login","duration":179566017,"bytes":0,"addr":"192.168.0.1","user":"-"}
{"time":"2025-05-19T16:20:52.969792524Z","level":"INFO","msg":"[request]","status":302,"method":"GET","uri":"/summary","duration":388809,"bytes":24,"addr":"192.168.0.1","user":"-"}
{"time":"2025-05-19T16:20:52.974805975Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/","duration":1064667,"bytes":8668,"addr":"192.168.0.1","user":"-"}
{"time":"2025-05-19T16:21:04.32931925Z","level":"INFO","msg":"[request]","status":302,"method":"GET","uri":"/summary","duration":386999,"bytes":24,"addr":"192.168.0.1","user":"-"}
{"time":"2025-05-19T16:21:04.33938056Z","level":"INFO","msg":"[request]","status":200,"method":"GET","uri":"/","duration":5091795,"bytes":8668,"addr":"192.168.0.1","user":"-"}
```

In my browser inspector, when I click the login button after entering my user info, I only see a 302 status code and I'm redirected to the home page. I'm not seeing any error anywhere.

Would you have any idea about what's happening?
