### ISSUE TITLE
Version 2.14 fails to connect to Postgres

### ISSUE THREAD

**Issue by nvroot** [muety/wakapi#806]
**Describe the bug**
```
Waiting for database to come up
wait-for-it.sh: waiting 60 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
/app/wait-for-it.sh: line 179: /app/wakapi: cannot execute binary file: Exec format error
/app/wait-for-it.sh: line 179: /app/wakapi: No error information
Waiting for database to come up
wait-for-it.sh: waiting 60 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
/app/wait-for-it.sh: line 179: /app/wakapi: cannot execute binary file: Exec format error
/app/wait-for-it.sh: line 179: /app/wakapi: No error information
```

**System information**
Please provide information on:
* Wakapi version = 2.14, latest, alpine
* Operating system:
    * Linux: 24.04 lts
    * Docker: wakapi:latest , postgres:17 and postgres:17-alpine
* Database (Postgres)

Same compose works perfectly up to 2.13.4:

```
services:
  wakapi:
    image: 'ghcr.io/muety/wakapi:latest'
    restart: unless-stopped
    environment:
      - WAKAPI_DB_TYPE=postgres
      - WAKAPI_DB_NAME=wakapi
      - WAKAPI_DB_USER=wakapi
      - WAKAPI_DB_HOST=postgres
      - WAKAPI_DB_PORT=5432
      - WAKAPI_DB_PASSWORD=changeme
      - WAKAPI_DB_SSL=false    # true doesn't works too
      - WAKAPI_PASSWORD_SALT=passwordsalt
      - WAKAPI_ALLOW_SIGNUP=true
      - WAKAPI_MAIL_ENABLED=false
      - 'WAKAPI_LEADERBOARD_GENERATION_TIME=0 0 * * * *'
      - 'WAKAPI_LEADERBOARD_SCOPE=all_time'
      - 'WAKAPI_LEADERBOARD_REQUIRE_AUTH=true'
      - 'WAKAPI_PORT=3000'
      - 'WAKAPI_PUBLIC_URL=https://waka.site.com'
      - 'WAKAPI_DISABLE_FRONTPAGE=true'
      - WAKAPI_MAIL_ENABLED=true
      - WAKAPI_MAIL_PROVIDER=smtp
      - WAKAPI_MAIL_SENDER=Wakapi
      - WAKAPI_MAIL_SMTP_HOST=smtp.site.com
      - WAKAPI_MAIL_SMTP_PORT=465
      - WAKAPI_MAIL_SMTP_USER=admin@site.com
      - WAKAPI_MAIL_SMTP_PASS=mailpassword
      - WAKAPI_MAIL_SMTP_TLS=true
    volumes:
      - 'wakapi-data:/data'
    networks:
      - wakapi-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
  postgres:
    image: 'postgres:17-alpine'
    restart: unless-stopped
    volumes:
      - 'wakapi-db:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=wakapi'
      - 'POSTGRES_PASSWORD=changeme'
      - 'POSTGRES_DB=wakapi'
    networks:
      - wakapi-network
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
volumes:
  wakapi-data:
  wakapi-db:
networks:
  wakapi-network:
```
