### ISSUE TITLE
2.14.0: receiving "Error: Resource not found" when hitting API and logging in via UI

### ISSUE THREAD

**Issue by lrstanley** [muety/wakapi#810]
**Describe the bug**

Upgrading to 2.14.0, and seeing the following error on the `POST` request to `/login` (after providing credentials) when logging in via the UI:

![](https://cdn.liam.sh/share/2025/06/firefox_wtpfzPFdwp.png)

Looks like it returns a 404 as a response to the `POST`.

I've since restored my DB, and rolled back to the previous WakAPI version, and it's working again.

Env vars I'm using:

```yaml
    - name: ENVIRONMENT
      value: prod
    - name: WAKAPI_ALLOW_SIGNUP
      value: "false"
    - name: WAKAPI_DB_HOST
      value: wakapi-postgres-rw
    - name: WAKAPI_DB_NAME
      value: app
    - name: WAKAPI_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: wakapi-postgres-app
    - name: WAKAPI_DB_PORT
      value: "5432"
    - name: WAKAPI_DB_TYPE
      value: postgres
    - name: WAKAPI_DB_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: wakapi-postgres-app
    - name: WAKAPI_DISABLE_FRONTPAGE
      value: "true"
    - name: WAKAPI_INSECURE_COOKIES
      value: "false"
    - name: WAKAPI_LEADERBOARD_ENABLED
      value: "false"
    - name: WAKAPI_LISTEN_IPV4
      value: 0.0.0.0
    - name: WAKAPI_PORT
      value: "3000"
    - name: WAKAPI_PUBLIC_URL
      value: https://wakapi.liam.sh
    - name: WAKAPI_PASSWORD_SALT
      valueFrom:
        secretKeyRef:
          key: WAKAPI_PASSWORD_SALT
          name: wakapi-env-vars
```

**System information**

* Wakapi version: 2.14.0
* Operating system
    * docker (kubernetes): `ghcr.io/muety/wakapi:2.14.0`
* Database: Postgres 17
