### ISSUE TITLE
aarch64 / arm64 Docker Image - startup error (2.14.0)

### ISSUE THREAD

**Issue by dontWatchMeCode** [muety/wakapi#812]
**Describe the bug**

Container throws the following error on startup:

Error Message:

```bash
wakapi    | /app/entrypoint.sh: line 32: /app/wakapi: cannot execute binary file: Exec format error
wakapi    | /app/entrypoint.sh: line 32: /app/wakapi: No error information
```

I am assuming its a problem with the arm container image.

Old version (2.13.4) works perfectly.

---

**System information**

OS: `Linux v220240876387283608 6.1.0-37-arm64 #1 SMP Debian 6.1.140-1 (2025-05-22) aarch64 GNU/Linux`

Podman version: 4.3.1

```yaml
services:
  wakapi:
    ports:
      - <...>
    environment:
      - WAKAPI_PASSWORD_SALT=<...>
      - WAKAPI_LEADERBOARD_ENABLED=false
      - WAKAPI_LEADERBOARD_REQUIRE_AUTH=true
      - ENVIRONMENT=prod
      - WAKAPI_ALLOW_SIGNUP=false
    volumes:
      - wakapi-data:/data
    image: ghcr.io/muety/wakapi:<2.13.4 / 2.14.0>
    restart: always

volumes:
  wakapi-data: {}

networks: {}
```

Tested Wakapi versions:

- 2.14.0 (latest) > doesn't work
- 2.13.4 > works
